/**
 * @license
 * Copyright 2025 Qwen Team
 * SPDX-License-Identifier: Apache-2.0
 */

export {
  DaemonClient,
  DaemonHttpError,
  type CreateSessionRequest,
  type DaemonClientOptions,
  type PromptRequest,
  type RestoreSessionRequest,
  type SubscribeOptions,
} from './DaemonClient.js';
export {
  DaemonAuthFlow,
  DEVICE_FLOW_EXPIRY_GRACE_MS,
  type AwaitCompletionOptions,
  type DaemonAuthFlowHandle,
} from './DaemonAuthFlow.js';
export {
  DaemonSessionClient,
  type DaemonSessionClientOptions,
  type DaemonSessionSubscribeOptions,
} from './DaemonSessionClient.js';
export {
  asKnownDaemonEvent,
  createDaemonAuthState,
  createDaemonSessionViewState,
  isDaemonEventType,
  isKnownDaemonEvent,
  // F2 (#4175 commit 6 review fix — claude-opus-4-7 W121): re-export
  // the workspace-scoped budget event helper. Pre-fix the PR
  // description and event JSDoc told consumers to use this helper to
  // branch on `scope === 'workspace'`, but the function lived in
  // `events.ts` and was never added to this barrel — SDK consumers
  // had no public import path. Same omission pattern caught for PR-21
  // auth surface; locked down by `daemon-public-surface.test.ts`.
  isWorkspaceScopedBudgetEvent,
  reduceDaemonAuthEvent,
  reduceDaemonAuthEvents,
  reduceDaemonSessionEvent,
  reduceDaemonSessionEvents,
} from './events.js';
export { parseSseStream, SseFramingError } from './sse.js';
export {
  appendLocalUserTranscriptMessage,
  createDaemonToolPreview,
  createDaemonTranscriptState,
  createDaemonTranscriptStore,
  DAEMON_PLAN_TOOL_CALL_ID,
  daemonBlockToHtml,
  daemonBlockToMarkdown,
  daemonBlockToPlainText,
  daemonToolPreviewToMarkdown,
  daemonUiEventToTerminalText,
  extractContentPart,
  formatBlockTimestamp,
  getOutputText as getDaemonUiOutputText,
  getSessionUpdatePayload,
  isDaemonUiSensitiveKey,
  isSubagentChildBlock,
  normalizeDaemonEvent,
  redactDaemonUiSensitiveFields,
  rebuildDaemonTranscriptBlockIndex,
  reduceDaemonTranscriptEvents,
  runAdapterConformanceSuite,
  sanitizeTerminalText as sanitizeDaemonTerminalText,
  selectApprovalMode,
  selectCurrentTool,
  selectPendingPermissionBlocks,
  selectSubagentChildBlocks,
  selectToolProgress,
  selectTranscriptBlocks,
  selectTranscriptBlocksOrderedByEventId,
  stringifyJson as stringifyDaemonUiJson,
  stripOscSequences as stripDaemonOscSequences,
  transcriptBlockToTerminalText,
  DAEMON_UI_CONFORMANCE_FIXTURES,
} from './ui/index.js';
export type {
  DaemonRenderOptions,
  DaemonHtmlRenderOptions,
  DaemonUiContentPart,
  DaemonUiAdapterUnderTest,
  DaemonUiConformanceFixture,
  ConformanceFailure,
  ConformanceSuiteResult,
  RunConformanceOptions,
} from './ui/index.js';
export type {
  DaemonShellTranscriptBlock,
  DaemonStatusTranscriptBlock,
  DaemonTextTranscriptBlock,
  DaemonToolPreview,
  DaemonToolTranscriptBlock,
  DaemonTranscriptBlock,
  DaemonTranscriptBlockKind,
  DaemonTranscriptQuestion,
  DaemonTranscriptQuestionOption,
  DaemonTranscriptReducerOptions,
  DaemonTranscriptSidechannelState,
  DaemonTranscriptState,
  DaemonTranscriptStore,
  DaemonUiAssistantDoneEvent,
  DaemonUiAuthDeviceFlowAuthorizedEvent,
  DaemonUiAuthDeviceFlowCancelledEvent,
  DaemonUiAuthDeviceFlowEvent,
  DaemonUiAuthDeviceFlowFailedEvent,
  DaemonUiAuthDeviceFlowStartedEvent,
  DaemonUiAuthDeviceFlowThrottledEvent,
  DaemonUiErrorEvent,
  DaemonUiEvent,
  DaemonUiEventBase,
  DaemonUiEventType,
  DaemonUiMcpBudgetWarningEvent,
  DaemonUiMcpChildRefusedEvent,
  DaemonUiMcpServerRestartedEvent,
  DaemonUiMcpServerRestartRefusedEvent,
  DaemonUiModelChangedEvent,
  DaemonUiPermissionOption,
  DaemonUiPermissionRequestEvent,
  DaemonUiPermissionResolvedEvent,
  DaemonUiSessionActions,
  DaemonUiSessionApprovalModeChangedEvent,
  DaemonUiSessionAvailableCommandsEvent,
  DaemonUiSessionMetadataChangedEvent,
  DaemonUiShellOutputEvent,
  DaemonUiStateResyncRequiredEvent,
  DaemonUiReplayCompleteEvent,
  DaemonUiPromptCancelledEvent,
  DaemonUiStatusEvent,
  DaemonUiTextEvent,
  DaemonUiToolProvenance,
  DaemonUiToolUpdateEvent,
  DaemonUiWorkspaceAgentChangedEvent,
  DaemonUiWorkspaceInitializedEvent,
  DaemonUiWorkspaceMemoryChangedEvent,
  DaemonUiWorkspaceToolToggledEvent,
  NormalizeDaemonEventOptions,
} from './ui/index.js';
export {
  DAEMON_APPROVAL_MODES,
  DAEMON_ERROR_KINDS,
  DaemonCapabilityMissingError,
  isDaemonContentHash,
  requireWorkspaceCwd,
} from './types.js';
export type {
  DaemonAgentChangedData,
  DaemonAgentChangedEvent,
  DaemonApprovalModeChangedData,
  DaemonApprovalModeChangedEvent,
  DaemonClientEvictedData,
  DaemonClientEvictedEvent,
  DaemonControlEvent,
  // #4175 F4 prereq (Ilya0527 issue #15) — daemon-emitted resync
  // signal for SSE reconnects past the ring eviction boundary.
  DaemonStateResyncRequiredData,
  DaemonStateResyncRequiredEvent,
  DaemonMcpServerRestartedData,
  DaemonMcpServerRestartedEvent,
  DaemonMcpServerRestartRefusedData,
  DaemonMcpServerRestartRefusedEvent,
  DaemonToolToggledData,
  DaemonToolToggledEvent,
  DaemonWorkspaceInitializedData,
  DaemonWorkspaceInitializedEvent,
  DaemonEventEnvelope,
  DaemonKnownEventType,
  // PR 14b — MCP guardrail push-event types. See `mcp_guardrail_events`
  // capability tag and the `DaemonMcpGuardrailEvent` union below.
  DaemonMcpBudgetWarningData,
  DaemonMcpBudgetWarningEvent,
  DaemonMcpChildRefusedBatchData,
  DaemonMcpChildRefusedBatchEvent,
  DaemonMcpGuardrailEvent,
  DaemonMcpRefusedServer,
  DaemonMemoryChangedData,
  DaemonMemoryChangedEvent,
  DaemonModelSwitchedData,
  DaemonModelSwitchedEvent,
  DaemonModelSwitchFailedData,
  DaemonModelSwitchFailedEvent,
  DaemonPermissionOption,
  DaemonPermissionAlreadyResolvedData,
  DaemonPermissionAlreadyResolvedEvent,
  // #4175 F3 Commit 7 — multi-client permission coordination push events.
  DaemonPermissionForbiddenData,
  DaemonPermissionForbiddenEvent,
  DaemonPermissionPartialVoteData,
  DaemonPermissionPartialVoteEvent,
  DaemonPermissionRequestData,
  DaemonPermissionRequestEvent,
  DaemonPermissionResolvedData,
  DaemonPermissionResolvedEvent,
  DaemonSessionClosedData,
  DaemonSessionClosedEvent,
  DaemonSessionClosedReason,
  DaemonSessionDiedData,
  DaemonSessionDiedEvent,
  DaemonSessionEvent,
  DaemonSessionMetadataUpdatedData,
  DaemonSessionMetadataUpdatedEvent,
  DaemonSessionUpdateData,
  DaemonSessionUpdateEvent,
  DaemonSessionViewState,
  DaemonSlowClientWarningData,
  DaemonSlowClientWarningEvent,
  DaemonStreamErrorData,
  DaemonStreamErrorEvent,
  DaemonStreamLifecycleEvent,
  DaemonWorkspaceMutationEvent,
  DaemonAuthDeviceFlowProviderId,
  DaemonAuthDeviceFlowStatus,
  DaemonAuthDeviceFlowErrorKind,
  DaemonAuthDeviceFlowStartedData,
  DaemonAuthDeviceFlowStartedEvent,
  DaemonAuthDeviceFlowThrottledData,
  DaemonAuthDeviceFlowThrottledEvent,
  DaemonAuthDeviceFlowAuthorizedData,
  DaemonAuthDeviceFlowAuthorizedEvent,
  DaemonAuthDeviceFlowFailedData,
  DaemonAuthDeviceFlowFailedEvent,
  DaemonAuthDeviceFlowCancelledData,
  DaemonAuthDeviceFlowCancelledEvent,
  DaemonAuthEvent,
  DaemonDeviceFlowReducerState,
  DaemonAuthState,
  KnownDaemonEvent,
} from './events.js';
export type {
  DaemonAgentLevel,
  DaemonAgentMutationResult,
  DaemonApprovalMode,
  DaemonApprovalModeResult,
  DaemonInitWorkspaceResult,
  DaemonMcpRestartResult,
  DaemonToolToggleResult,
  DaemonAvailableCommand,
  DaemonCapabilities,
  DaemonContextFileScope,
  DaemonCreateAgentRequest,
  DaemonEnvCell,
  DaemonEnvKind,
  DaemonErrorKind,
  DaemonEvent,
  DaemonMcpDiscoveryState,
  DaemonMcpServerRuntimeStatus,
  DaemonMcpTransport,
  DaemonMode,
  DaemonProtocolVersions,
  DaemonRestoredSession,
  DaemonSession,
  DaemonAuthProviderId,
  DaemonAuthDeviceFlowSdkStatus,
  DaemonAuthDeviceFlowSdkErrorKind,
  DaemonAuthProviderStatus,
  DaemonAuthStatusSnapshot,
  DaemonDeviceFlowStartResult,
  DaemonDeviceFlowState,
  DaemonSessionContextStatus,
  DaemonSessionState,
  DaemonSessionSummary,
  DaemonSessionSupportedCommandsStatus,
  DaemonSkillLevel,
  DaemonPreflightCell,
  DaemonPreflightKind,
  DaemonStatus,
  DaemonStatusCell,
  DaemonUpdateAgentRequest,
  DaemonContentHash,
  DaemonWorkspaceAgentDetail,
  DaemonWorkspaceAgentSummary,
  DaemonWorkspaceAgentsStatus,
  DaemonWorkspaceEnvStatus,
  DaemonWorkspaceFile,
  DaemonWorkspaceFileBytes,
  DaemonWorkspaceFileEditRequest,
  DaemonWorkspaceFileEditResult,
  DaemonWorkspaceFileWriteRequest,
  DaemonWorkspaceFileWriteResult,
  DaemonWorkspaceMcpServerStatus,
  DaemonWorkspaceMcpStatus,
  DaemonWorkspaceMemoryFile,
  DaemonWorkspaceMemoryStatus,
  DaemonWorkspacePreflightStatus,
  DaemonWorkspaceProviderCurrent,
  DaemonWorkspaceProviderModel,
  DaemonWorkspaceProviderStatus,
  DaemonWorkspaceProvidersStatus,
  DaemonWorkspaceSkillStatus,
  DaemonWorkspaceSkillsStatus,
  DaemonWriteMemoryRequest,
  DaemonWriteMemoryResult,
  HeartbeatResult,
  PermissionOutcome,
  PermissionOutcomeCancelled,
  PermissionOutcomeSelected,
  PermissionResponse,
  PromptContentBlock,
  PromptResult,
  PromptTextContent,
  SetModelResult,
  SessionMetadataResult,
} from './types.js';
