/**
 * @license
 * Copyright 2025 Qwen Code
 * SPDX-License-Identifier: Apache-2.0
 */

import type { SupportedLanguage } from './types';

// Translation dictionary for insight report UI
export const translations: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    // Header
    'Qwen Code Insights': 'Qwen Code Insights',
    'messages across': 'messages across',
    sessions: 'sessions',

    // Export
    'Export Card': 'Export Card',
    Dark: 'Dark',
    Light: 'Light',

    // At a Glance
    'At a Glance': 'At a Glance',
    "What's working:": "What's working:",
    "What's hindering you:": "What's hindering you:",
    'Quick wins to try:': 'Quick wins to try:',
    'Ambitious workflows:': 'Ambitious workflows:',
    'Impressive Things You Did →': 'Impressive Things You Did →',
    'Where Things Go Wrong →': 'Where Things Go Wrong →',
    'Features to Try →': 'Features to Try →',
    'On the Horizon →': 'On the Horizon →',

    // Navigation
    'What You Work On': 'What You Work On',
    'How You Use Qwen Code': 'How You Use Qwen Code',
    'Impressive Things': 'Impressive Things',
    'Where Things Go Wrong': 'Where Things Go Wrong',
    'Features to Try': 'Features to Try',
    'New Usage Patterns': 'New Usage Patterns',
    'On the Horizon': 'On the Horizon',

    // Stats
    Messages: 'Messages',
    Lines: 'Lines',
    Files: 'Files',
    Days: 'Days',
    'Msgs/Day': 'Msgs/Day',

    // Project Areas
    'What You Wanted': 'What You Wanted',
    'Top Tools Used': 'Top Tools Used',

    // Interaction Style
    'Key pattern:': 'Key pattern:',

    // Impressive Workflows
    'Impressive Things You Did': 'Impressive Things You Did',
    "What Helped Most (Qwen's Capabilities)":
      "What Helped Most (Qwen's Capabilities)",
    Outcomes: 'Outcomes',

    // Friction Points
    'User Satisfaction': 'User Satisfaction',
    'Friction Categories': 'Friction Categories',

    // Improvements
    'QWEN.MD Additions': 'QWEN.MD Additions',
    'Usage Patterns': 'Usage Patterns',
    Copy: 'Copy',
    Copied: 'Copied!',

    // Memorable Moment
    'Memorable Moment': 'Memorable Moment',

    // Share Card
    'Share Your Insights': 'Share Your Insights',
    'Generated by Qwen Code': 'Generated by Qwen Code',
  },
  zh: {
    // Header
    'Qwen Code Insights': 'Qwen Code 洞察报告',
    'messages across': '条消息，跨越',
    sessions: '个会话',

    // Export
    'Export Card': '导出卡片',
    Dark: '深色',
    Light: '浅色',

    // At a Glance
    'At a Glance': '一览',
    "What's working:": '有效的方法：',
    "What's hindering you:": '阻碍你的因素：',
    'Quick wins to try:': '快速尝试的技巧：',
    'Ambitious workflows:': '雄心勃勃的工作流：',
    'Impressive Things You Did →': '你的出色表现 →',
    'Where Things Go Wrong →': '问题出在哪里 →',
    'Features to Try →': '尝试的功能 →',
    'On the Horizon →': '未来展望 →',

    // Navigation
    'What You Work On': '工作内容',
    'How You Use Qwen Code': '使用方式',
    'Impressive Things': '出色表现',
    'Where Things Go Wrong': '问题所在',
    'Features to Try': '功能推荐',
    'New Usage Patterns': '新的使用模式',
    'On the Horizon': '未来展望',

    // Stats
    Messages: '消息数',
    Lines: '代码行',
    Files: '文件数',
    Days: '天数',
    'Msgs/Day': '消息/天',

    // Project Areas
    'What You Wanted': '你的目标',
    'Top Tools Used': '常用工具',

    // Interaction Style
    'Key pattern:': '关键模式：',

    // Impressive Workflows
    'Impressive Things You Did': '你的出色表现',
    "What Helped Most (Qwen's Capabilities)": '最有帮助的功能',
    Outcomes: '结果',

    // Friction Points
    'User Satisfaction': '用户满意度',
    'Friction Categories': '摩擦类别',

    // Improvements
    'QWEN.MD Additions': 'QWEN.MD 建议',
    'Usage Patterns': '使用模式',
    Copy: '复制',
    Copied: '已复制！',

    // Memorable Moment
    'Memorable Moment': '难忘时刻',

    // Share Card
    'Share Your Insights': '分享你的洞察',
    'Generated by Qwen Code': '由 Qwen Code 生成',
  },
  ja: {
    // Header
    'Qwen Code Insights': 'Qwen Code インサイト',
    'messages across': '件のメッセージ、',
    sessions: 'セッション',

    // Export
    'Export Card': 'カードをエクスポート',
    Dark: 'ダーク',
    Light: 'ライト',

    // At a Glance
    'At a Glance': '概要',
    "What's working:": 'うまくいっていること：',
    "What's hindering you:": '妨げになっていること：',
    'Quick wins to try:': '簡単に試せること：',
    'Ambitious workflows:': '野心的なワークフロー：',
    'Impressive Things You Did →': 'あなたの素晴らしい成果 →',
    'Where Things Go Wrong →': '問題が発生する場所 →',
    'Features to Try →': '試すべき機能 →',
    'On the Horizon →': '将来の展望 →',

    // Navigation
    'What You Work On': '作業内容',
    'How You Use Qwen Code': 'Qwen Code の使用方法',
    'Impressive Things': '素晴らしい成果',
    'Where Things Go Wrong': '問題点',
    'Features to Try': '試す機能',
    'New Usage Patterns': '新しい使用パターン',
    'On the Horizon': '将来の展望',

    // Stats
    Messages: 'メッセージ',
    Lines: '行',
    Files: 'ファイル',
    Days: '日',
    'Msgs/Day': 'メッセージ/日',

    // Project Areas
    'What You Wanted': 'あなたの目標',
    'Top Tools Used': '使用したツール',

    // Interaction Style
    'Key pattern:': 'キーパターン：',

    // Impressive Workflows
    'Impressive Things You Did': 'あなたの素晴らしい成果',
    "What Helped Most (Qwen's Capabilities)": '最も役立った機能',
    Outcomes: '結果',

    // Friction Points
    'User Satisfaction': 'ユーザー満足度',
    'Friction Categories': '摩擦カテゴリ',

    // Improvements
    'QWEN.MD Additions': 'QWEN.MD 追加事項',
    'Usage Patterns': '使用パターン',
    Copy: 'コピー',
    Copied: 'コピー完了！',

    // Memorable Moment
    'Memorable Moment': '思い出深い瞬間',

    // Share Card
    'Share Your Insights': 'インサイトを共有',
    'Generated by Qwen Code': 'Qwen Code によって生成',
  },
  de: {
    // Header
    'Qwen Code Insights': 'Qwen Code Einblicke',
    'messages across': 'Nachrichten in',
    sessions: 'Sitzungen',

    // Export
    'Export Card': 'Karte exportieren',
    Dark: 'Dunkel',
    Light: 'Hell',

    // At a Glance
    'At a Glance': 'Auf einen Blick',
    "What's working:": 'Was funktioniert:',
    "What's hindering you:": 'Was hindert Sie:',
    'Quick wins to try:': 'Schnelle Erfolge:',
    'Ambitious workflows:': 'Ambitionierte Workflows:',
    'Impressive Things You Did →': 'Ihre beeindruckenden Leistungen →',
    'Where Things Go Wrong →': 'Wo Dinge schiefgehen →',
    'Features to Try →': 'Ausprobierenswerte Funktionen →',
    'On the Horizon →': 'Ausblick →',

    // Navigation
    'What You Work On': 'Woran Sie arbeiten',
    'How You Use Qwen Code': 'Wie Sie Qwen Code verwenden',
    'Impressive Things': 'Beeindruckende Dinge',
    'Where Things Go Wrong': 'Problembereiche',
    'Features to Try': 'Ausprobierenswerte Funktionen',
    'New Usage Patterns': 'Neue Nutzungsmuster',
    'On the Horizon': 'Ausblick',

    // Stats
    Messages: 'Nachrichten',
    Lines: 'Zeilen',
    Files: 'Dateien',
    Days: 'Tage',
    'Msgs/Day': 'Nachr./Tag',

    // Project Areas
    'What You Wanted': 'Ihre Ziele',
    'Top Tools Used': 'Häufig genutzte Tools',

    // Interaction Style
    'Key pattern:': 'Hauptmuster:',

    // Impressive Workflows
    'Impressive Things You Did': 'Ihre beeindruckenden Leistungen',
    "What Helped Most (Qwen's Capabilities)": 'Was am meisten half',
    Outcomes: 'Ergebnisse',

    // Friction Points
    'User Satisfaction': 'Benutzerzufriedenheit',
    'Friction Categories': 'Reibungspunkte',

    // Improvements
    'QWEN.MD Additions': 'QWEN.MD Ergänzungen',
    'Usage Patterns': 'Nutzungsmuster',
    Copy: 'Kopieren',
    Copied: 'Kopiert!',

    // Memorable Moment
    'Memorable Moment': 'Denkwürdiger Moment',

    // Share Card
    'Share Your Insights': 'Einblicke teilen',
    'Generated by Qwen Code': 'Generiert von Qwen Code',
  },
  pt: {
    // Header
    'Qwen Code Insights': 'Qwen Code Insights',
    'messages across': 'mensagens em',
    sessions: 'sessões',

    // Export
    'Export Card': 'Exportar Cartão',
    Dark: 'Escuro',
    Light: 'Claro',

    // At a Glance
    'At a Glance': 'Resumo',
    "What's working:": 'O que está funcionando:',
    "What's hindering you:": 'O que está dificultando:',
    'Quick wins to try:': 'Vitórias rápidas:',
    'Ambitious workflows:': 'Fluxos ambiciosos:',
    'Impressive Things You Did →': 'Suas Conquistas Impressionantes →',
    'Where Things Go Wrong →': 'Onde as Coisas Dão Errado →',
    'Features to Try →': 'Recursos para Experimentar →',
    'On the Horizon →': 'No Horizonte →',

    // Navigation
    'What You Work On': 'Em Que Você Trabalha',
    'How You Use Qwen Code': 'Como Você Usa Qwen Code',
    'Impressive Things': 'Conquistas Impressionantes',
    'Where Things Go Wrong': 'Onde as Coisas Dão Errado',
    'Features to Try': 'Recursos para Experimentar',
    'New Usage Patterns': 'Novos Padrões de Uso',
    'On the Horizon': 'No Horizonte',

    // Stats
    Messages: 'Mensagens',
    Lines: 'Linhas',
    Files: 'Arquivos',
    Days: 'Dias',
    'Msgs/Day': 'Mens./Dia',

    // Project Areas
    'What You Wanted': 'O Que Você Quis',
    'Top Tools Used': 'Ferramentas Mais Usadas',

    // Interaction Style
    'Key pattern:': 'Padrão principal:',

    // Impressive Workflows
    'Impressive Things You Did': 'Suas Conquistas Impressionantes',
    "What Helped Most (Qwen's Capabilities)": 'O Que Mais Ajudou',
    Outcomes: 'Resultados',

    // Friction Points
    'User Satisfaction': 'Satisfação do Usuário',
    'Friction Categories': 'Categorias de Atrito',

    // Improvements
    'QWEN.MD Additions': 'Adições QWEN.MD',
    'Usage Patterns': 'Padrões de Uso',
    Copy: 'Copiar',
    Copied: 'Copiado!',

    // Memorable Moment
    'Memorable Moment': 'Momento Memorável',

    // Share Card
    'Share Your Insights': 'Compartilhar Insights',
    'Generated by Qwen Code': 'Gerado por Qwen Code',
  },
  ru: {
    // Header
    'Qwen Code Insights': 'Qwen Code Инсайты',
    'messages across': 'сообщений в',
    sessions: 'сессиях',

    // Export
    'Export Card': 'Экспорт карточки',
    Dark: 'Тёмная',
    Light: 'Светлая',

    // At a Glance
    'At a Glance': 'Вкратце',
    "What's working:": 'Что работает:',
    "What's hindering you:": 'Что мешает:',
    'Quick wins to try:': 'Быстрые победы:',
    'Ambitious workflows:': 'Амбициозные рабочие процессы:',
    'Impressive Things You Did →': 'Ваши впечатляющие достижения →',
    'Where Things Go Wrong →': 'Где что-то идёт не так →',
    'Features to Try →': 'Функции для проб →',
    'On the Horizon →': 'На горизонте →',

    // Navigation
    'What You Work On': 'Над чем вы работаете',
    'How You Use Qwen Code': 'Как вы используете Qwen Code',
    'Impressive Things': 'Впечатляющие вещи',
    'Where Things Go Wrong': 'Где что-то идёт не так',
    'Features to Try': 'Функции для проб',
    'New Usage Patterns': 'Новые шаблоны использования',
    'On the Horizon': 'На горизонте',

    // Stats
    Messages: 'Сообщения',
    Lines: 'Строки',
    Files: 'Файлы',
    Days: 'Дни',
    'Msgs/Day': 'Сообщ./день',

    // Project Areas
    'What You Wanted': 'Чего вы хотели',
    'Top Tools Used': 'Используемые инструменты',

    // Interaction Style
    'Key pattern:': 'Ключевой паттерн:',

    // Impressive Workflows
    'Impressive Things You Did': 'Ваши впечатляющие достижения',
    "What Helped Most (Qwen's Capabilities)": 'Что помогло больше всего',
    Outcomes: 'Результаты',

    // Friction Points
    'User Satisfaction': 'Удовлетворённость пользователя',
    'Friction Categories': 'Категории трений',

    // Improvements
    'QWEN.MD Additions': 'Дополнения QWEN.MD',
    'Usage Patterns': 'Шаблоны использования',
    Copy: 'Копировать',
    Copied: 'Скопировано!',

    // Memorable Moment
    'Memorable Moment': 'Запоминающийся момент',

    // Share Card
    'Share Your Insights': 'Поделиться инсайтами',
    'Generated by Qwen Code': 'Сгенерировано Qwen Code',
  },
};

// Helper function to get translation
export function t(key: string, lang: SupportedLanguage = 'en'): string {
  return translations[lang]?.[key] ?? translations['en']?.[key] ?? key;
}
